### PR TITLE
fix issue with invisible parent

### PR DESCRIPTION
**Pull request by Stefan-vs**
this fixes an issue in the shopper app on ios, which causes the grocerylist to be invisible

### CODE REVIEW

**Comment by wvengen** [comment]
Cool! Some small questions:
- What's the change needed, and what are version updates?
- How does this relate to the [android-support](https://github.com/q-m/react-native-swipeout/tree/android-support) branch? Some changes look somewhat related.

**Comment by Stefan-vs** [comment]
I noticed the problem while running the android (merged) branch of the shopper app on iOS.
I updated the plugin, but the problem persisted, until I edited the style of the plugin talked about [here](https://github.com/dancormier/react-native-swipeout/issues/48).

The commits that look related in other branches are commits that are now part of the master branch (in the updated version of the plugin).

So the fix is just a tiny styling thing, the other stuff is because of updating the plugin. This is the code I've tested and I've got working in the merged version of the app.

**Comment by wvengen** [comment]
Thanks for explaining, looks good!

**Comment by wvengen** [comment]
For the future (Android compatibility on real devices): we may want to change the `=== 0` to something less precise (small movements on touch events) as in the [android-support](https://github.com/q-m/react-native-swipeout/commit/ce2b048498c301d73c45c45d8ef5c36a2dba7840) branch commit. But that's another issue, for later.

**Comment by s-andringa** [comment]
Looks good to merge if the drawbacks of not using `StyleSheet.create` were carefully considered. (I know it's less memory efficient, but other than that I cannot think of unintended side effects.)

**Comment by wvengen** [comment]
@s-andringa this change has happened upstream as well, so I guess it's carefully considered.

**Pull request merged**
